# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/units.tsv

# optional inclusion of certain rules -------------------------------------------------------
mergeReads:
  activate: False

# text file containing list of chromosomes to keep when filtering ---------------------------
filter_chroms: True
keep_chroms: config/keep_chroms.txt

# reference genome options ------------------------------------------------------------------
ref_genome:
  name: dm6
  link: https://hgdownload.soe.ucsc.edu/goldenPath/dm6/bigZips/dm6.fa.gz

use_spikeIn: False

# DESeq2 options -------------------------------------------------------------------------
run_diff_accessibility: TRUE
diff_accessibility:
  experiments: # each entry here should match the entries in the experiment column of samples.tsv
    GAF_ATACseq:
      # contrasts for the deseq2 results method. These should match the entries in the condition column of samples.tsv
      contrasts:
        degrad-vs-control:
          - degrad
          - control
  model: ~condition
  count_threshold: 50
  padj_cutoff: 0.05
  log2FC_cutoff: 1

# changes to rule paramters ---------------------------------------------------------------
# Alignment
params:
  bowtie2_index: ""
  bowtie2_align: "-k 2 --very-sensitive --no-mixed --no-discordant -X 5000"

  # Filter reads
  filter_multireads: "-q 0"   # keep all reads with mapping quality >=0

  # Preprocessing
  samtools_sort_by_name: "-n"
  samtools_fixmate: "-m"
  samtools_sort_position: ""   # default position sort

  # Duplicate handling
  samtools_markdup: "-s"       # mark duplicates instead of removing
  samtools_index_dedup: ""     # index after markdup

  # Bigwig generation
  bigwigs_ind: "--binSize 10"
  bigwigs_merged: "--binSize 10"

  # MACS2 peak calling
  macs2_call_atac_peaks_ind: "-f BAMPE --keep-dup all -g dm --call-summits"
  macs2_call_atac_peaks_merged: "-f BAMPE --keep-dup all -g dm --call-summits"
